services:
  fastapi:
    build: .
    container_name: fastapi
    restart: always
    expose:
      - "8000"
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /home/ubuntu/SoomterFront:/usr/share/nginx/html:ro  # 이거 추가!
    depends_on:
      - fastapi
    networks:
      - backend

volumes:
  mariadb_data:

networks:
  backend: